FROM node:alpine

WORKDIR /usr/src/app

ENV NODE_ENV development

COPY package*.json ./

RUN npm install

COPY . .

COPY entrypoint.dev.sh .

EXPOSE 4200

RUN chmod +x /usr/src/app/entrypoint.dev.sh
ENTRYPOINT [ "sh", "/usr/src/app/entrypoint.dev.sh" ]